### ISSUE TITLE
Proper Wave Names 

### ISSUE THREAD

**Issue by KLD** [KLD/Alebi#63]
Wave name should reflect the uniqueness of the wave, and it's major contents.  

I think names like 'KLD Wave 1' are obviously bad. 

Why does it matter? 
Because we write code related to it, and bad naming is always bad: 
![image](https://user-images.githubusercontent.com/4420439/38776371-1945a484-409e-11e8-9b12-b31a160f2e81.png)
![image](https://user-images.githubusercontent.com/4420439/38776376-29554960-409e-11e8-85fa-9dfd9b0d1e94.png)
![image](https://user-images.githubusercontent.com/4420439/38776377-2d175912-409e-11e8-8ae4-ededa75dcf07.png)
All of these are poorly named partly because their root, Wave name, is also not named properly. 

So, let's give good names, so that when we have children, we may name them properly too. 

Currently, we have 4 waves: 
- **Wave Name : Wave's Theme**
- KLD Wave 1 : Net and Coins.
- Rave Wave : Circular Dagger and center sand.
- Continuoes Wave : Oil, Weapon, and Coins.
- Ahmed's Wave  : Shattering Gems and Daggers

For any wave, let us suggest a name that would indicate the wave's theme. What creative names can we come up with? 

I'll try give my own: 
- KLD Wave 1 --> Standard Net Wave 
- Rave Wave --> Sand Spine Wave 
- Continuoes Wave  --> Standard Oil & Weapon Wave 
- Ahmed's Wave --> Shatter Gem Wave

**Comment by ChainedRam** [comment]
KLD Wave 1 --> Net Wave (N)
Rave Wave --> Sand Wave (S)
Continuoes Wave --> Weapon Wave (W)
Ahmed's Wave --> Gem Wave (G)
